executors:
  ruby_with_db:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
      - image: circleci/postgres:12.1-alpine-ram
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432'

jobs:
  integration-tests:
    executor: ruby_with_db
    steps:
      - checkout:
          path: /tmp/rails-orbs
      - run: cp -rT /tmp/rails-orbs/test/app .
      - rails/bundle-install
      - rails/yarn-install
      - rails/assets-precompile
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bin/rails db:create db:test:prepare
      - ruby/run-tests
orbs:
  orb-tools: circleci/orb-tools@9.0.0
  rails: medpeer/rails@<<pipeline.parameters.dev-orb-version>>
  ruby: circleci/ruby@0.2.1
parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    default: false
    type: boolean
version: 2.1
workflows:
  integration-tests_prod-release:
    jobs:
      - integration-tests
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          filters:
            branches:
              only: master
          orb-name: medpeer/rails
          publish-version-tag: false
          requires:
            - integration-tests
    when: << pipeline.parameters.run-integration-tests >>
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: medpeer/rails
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
